/*
 * pshot - Photoshop CS6 menu bar (see docs/cs6-spec.md §4).
 *
 * Compact notation, parsed below into the menu schema used by gui-menu.js:
 *   '-'                                  separator
 *   'Name|Shortcut|module/file.function' item (shortcut and target optional)
 *   ['Name', [...children]]              submenu
 *   { ...object }                        passed through as-is (e.g. checked)
 * An item without a target is a CS6 feature pshot doesn't have yet: it is
 * rendered in place but disabled.
 */

const M = [
	['File', [
		'New...|Ctrl+N|ps/commands.new_document',
		'Open...|Ctrl+O|ps/commands.open',
		'Browse in Bridge...|Alt+Ctrl+O',
		'Browse in Mini Bridge...',
		'Open As...|Alt+Shift+Ctrl+O|ps/commands.open',
		'Open as Smart Object...',
		['Open Recent', []],
		'-',
		'Close|Ctrl+W|ps/commands.close_document',
		'Close All|Alt+Ctrl+W|ps/commands.close_all',
		'Close and Go to Bridge...|Shift+Ctrl+W',
		'Save|Ctrl+S|ps/commands.save',
		'Save As...|Shift+Ctrl+S|file/save.save',
		'Check In...',
		'Save for Web...|Alt+Shift+Ctrl+S|file/save.export',
		'Revert|F12|ps/commands.revert',
		'-',
		'Place...|ps/commands.place',
		'-',
		['Import', ['Variable Data Sets...', 'Video Frames to Layers...', 'Notes...', 'WIA Support...']],
		['Export', ['Data Sets as Files...', 'Paths to Illustrator...', 'Render Video...', 'Zoomify...']],
		'-',
		['Automate', ['Batch...', 'PDF Presentation...', 'Create Droplet...', '-', 'Crop and Straighten Photos', '-', 'Contact Sheet II...', '-', 'Conditional Mode Change...', 'Fit Image...', 'Lens Correction...', 'Merge to HDR Pro...', 'Photomerge...']],
		['Scripts', ['Image Processor...', '-', 'Delete All Empty Layers|ps/commands.delete_empty_layers', 'Flatten All Layer Effects', 'Flatten All Masks', '-', 'Layer Comps to Files...', 'Layer Comps to PDF...', 'Layer Comps to WPG...', 'Export Layers to Files...', '-', 'Script Events Manager...', '-', 'Load Files into Stack...', 'Load Multiple DICOM Files...', 'Statistics...', '-', 'Browse...']],
		'-',
		'File Info...|Alt+Shift+Ctrl+I|image/information.information',
		'-',
		'Print...|Ctrl+P|file/print.print',
		'Print One Copy|Alt+Shift+Ctrl+P|file/print.print',
		'-',
		'Exit|Ctrl+Q',
	]],
	['Edit', [
		{ name: 'Undo', shortcut: 'Ctrl+Z', target: 'ps/commands.toggle_undo', dynamic_name: 'undo_label' },
		'Step Forward|Shift+Ctrl+Z|edit/redo.redo',
		'Step Backward|Alt+Ctrl+Z|edit/undo.undo',
		'-',
		'Fade...|Shift+Ctrl+F|ps/commands.fade',
		'-',
		'Cut|Ctrl+X|ps/commands.cut',
		'Copy|Ctrl+C|ps/commands.copy',
		'Copy Merged|Shift+Ctrl+C|ps/commands.copy_merged',
		'Paste|Ctrl+V|ps/commands.paste',
		['Paste Special', ['Paste in Place|Shift+Ctrl+V|ps/commands.paste_in_place', 'Paste Into|Alt+Shift+Ctrl+V|ps/commands.paste_into', 'Paste Outside|ps/commands.paste_outside']],
		'Clear|ps/commands.clear',
		'-',
		'Check Spelling...',
		'Find and Replace Text...',
		'-',
		'Fill...|Shift+F5|ps/commands.fill',
		'Stroke...|ps/commands.stroke',
		'-',
		'Content-Aware Scale|Alt+Shift+Ctrl+C',
		'Puppet Warp',
		'Free Transform|Ctrl+T|ps/commands.free_transform',
		['Transform', [
			'Again|Shift+Ctrl+T|ps/commands.transform_again', '-',
			'Scale|ps/commands.free_transform', 'Rotate|ps/commands.free_transform', 'Skew|ps/commands.transform_skew', 'Distort|ps/commands.transform_distort', 'Perspective|ps/commands.transform_perspective', 'Warp', '-',
			'Rotate 180°|ps/commands.rotate_layer_180', 'Rotate 90° CW|image/rotate.right', 'Rotate 90° CCW|image/rotate.left', '-',
			'Flip Horizontal|image/flip.horizontal', 'Flip Vertical|image/flip.vertical',
		]],
		'Auto-Align Layers...',
		'Auto-Blend Layers...',
		'-',
		'Define Brush Preset...',
		'Define Pattern...|ps/commands.define_pattern',
		'Define Custom Shape...',
		'-',
		['Purge', ['Undo', 'Clipboard', 'Histories|ps/commands.purge_histories', 'Video Cache', 'All|ps/commands.purge_histories']],
		'-',
		'Adobe PDF Presets...',
		['Presets', ['Preset Manager...', 'Migrate Presets', 'Export/Import Presets...']],
		'Remote Connections...',
		'-',
		'Color Settings...|Shift+Ctrl+K',
		'Assign Profile...',
		'Convert to Profile...',
		'-',
		'Keyboard Shortcuts...|Alt+Shift+Ctrl+K|help/shortcuts.shortcuts',
		'Menus...|Alt+Shift+Ctrl+M',
		['Preferences', [
			'General...|Ctrl+K|tools/settings.settings', 'Interface...|tools/settings.settings', 'File Handling...', 'Performance...', 'Cursors...', 'Transparency & Gamut...|tools/settings.settings', 'Units & Rulers...', 'Guides, Grid & Slices...', 'Plug-Ins...', 'Type...', '3D...', '-', 'Camera Raw...',
		]],
	]],
	['Image', [
		['Mode', [
			'Bitmap...', 'Grayscale', 'Duotone...', 'Indexed Color...|image/decrease_colors.decrease_colors', { name: 'RGB Color', checked: true, target: 'ps/commands.noop' }, 'CMYK Color', 'Lab Color', 'Multichannel', '-',
			{ name: '8 Bits/Channel', checked: true, target: 'ps/commands.noop' }, '16 Bits/Channel', '32 Bits/Channel', '-', 'Color Table...',
		]],
		'-',
		['Adjustments', [
			'Brightness/Contrast...|ps/commands.brightness_contrast', 'Levels...|Ctrl+L|ps/commands.levels', 'Curves...|Ctrl+M|ps/commands.curves', 'Exposure...|ps/commands.exposure', '-',
			'Vibrance...|ps/commands.vibrance', 'Hue/Saturation...|Ctrl+U|ps/commands.hue_saturation', 'Color Balance...|Ctrl+B|ps/commands.color_balance', 'Black & White...|Alt+Shift+Ctrl+B|effects/black_and_white.black_and_white', 'Photo Filter...|ps/commands.photo_filter', 'Channel Mixer...|ps/commands.channel_mixer', 'Color Lookup...', '-',
			'Invert|Ctrl+I|effects/common/invert.invert', 'Posterize...|image/decrease_colors.decrease_colors', 'Threshold...|effects/black_and_white.black_and_white', 'Gradient Map...|ps/commands.gradient_map', 'Selective Color...|ps/commands.selective_color', '-',
			'Shadows/Highlights...|ps/commands.shadows_highlights', 'HDR Toning...', 'Variations...', '-',
			'Desaturate|Shift+Ctrl+U|effects/common/grayscale.grayscale', 'Match Color...', 'Replace Color...|tools/replace_color.replace_color', 'Equalize|ps/commands.equalize',
		]],
		'-',
		'Auto Tone|Shift+Ctrl+L|image/auto_adjust.auto_adjust',
		'Auto Contrast|Alt+Shift+Ctrl+L|image/auto_adjust.auto_adjust',
		'Auto Color|Shift+Ctrl+B|image/auto_adjust.auto_adjust',
		'-',
		'Image Size...|Alt+Ctrl+I|ps/commands.image_size',
		'Canvas Size...|Alt+Ctrl+C|ps/commands.canvas_size',
		['Image Rotation', ['180°|ps/commands.rotate_canvas_180', '90° CW|ps/commands.rotate_canvas_cw', '90° CCW|ps/commands.rotate_canvas_ccw', 'Arbitrary...|image/rotate.rotate', '-', 'Flip Canvas Horizontal|ps/commands.flip_canvas_h', 'Flip Canvas Vertical|ps/commands.flip_canvas_v']],
		'Crop|ps/commands.crop_to_selection',
		'Trim...|image/trim.trim',
		'Reveal All|ps/commands.reveal_all',
		'-',
		'Duplicate...|ps/commands.duplicate_document',
		'Apply Image...',
		'Calculations...',
		'-',
		['Variables', ['Define...', 'Data Sets...']],
		'Apply Data Set...',
		'-',
		'Trap...',
		'-',
		['Analysis', [['Set Measurement Scale', ['Default', 'Custom...']], ['Select Data Points', ['Default', 'Custom...']], 'Record Measurements|Shift+Ctrl+M', '-', 'Ruler Tool', 'Count Tool', '-', 'Place Scale Marker...']],
	]],
	['Layer', [
		['New', ['Layer...|Shift+Ctrl+N|layer/new.new', 'Background from Layer|ps/commands.background_from_layer', 'Group...|ps/commands.new_group', 'Group from Layers...|ps/commands.group_layers', '-', 'Layer via Copy|Ctrl+J|ps/commands.layer_via_copy', 'Layer via Cut|Shift+Ctrl+J|ps/commands.layer_via_cut']],
		'Duplicate Layer...|layer/duplicate.duplicate',
		['Delete', ['Layer|ps/commands.delete_layer', 'Hidden Layers|ps/commands.delete_hidden_layers']],
		'-',
		['Layer Style', [
			{ name: 'Blending Options...', target: 'ps/commands.layer_style', parameter: 'blending' }, '-',
			{ name: 'Bevel & Emboss...', target: 'ps/commands.layer_style', parameter: 'bevel' },
			{ name: 'Stroke...', target: 'ps/commands.layer_style', parameter: 'stroke' },
			{ name: 'Inner Shadow...', target: 'ps/commands.layer_style', parameter: 'inner_shadow' },
			{ name: 'Inner Glow...', target: 'ps/commands.layer_style', parameter: 'inner_glow' },
			{ name: 'Satin...', target: 'ps/commands.layer_style', parameter: 'satin' },
			{ name: 'Color Overlay...', target: 'ps/commands.layer_style', parameter: 'color_overlay' },
			{ name: 'Gradient Overlay...', target: 'ps/commands.layer_style', parameter: 'gradient_overlay' },
			{ name: 'Pattern Overlay...', target: 'ps/commands.layer_style', parameter: 'pattern_overlay' },
			{ name: 'Outer Glow...', target: 'ps/commands.layer_style', parameter: 'outer_glow' },
			{ name: 'Drop Shadow...', target: 'ps/commands.layer_style', parameter: 'drop_shadow' }, '-',
			'Copy Layer Style|ps/commands.copy_layer_style', 'Paste Layer Style|ps/commands.paste_layer_style', 'Clear Layer Style|ps/commands.clear_layer_style', '-',
			'Global Light...', 'Create Layer', 'Hide All Effects', 'Scale Effects...',
		]],
		['Smart Filter', ['Disable Smart Filters', 'Delete Filter Mask', 'Disable Filter Mask', 'Clear Smart Filters']],
		'-',
		['New Fill Layer', ['Solid Color...|ps/commands.new_fill_layer', 'Gradient...|ps/commands.new_gradient_fill_layer', 'Pattern...|ps/commands.new_pattern_fill_layer']],
		['New Adjustment Layer', [{ name: 'Brightness/Contrast...', target: 'ps/commands.new_adjustment_layer', parameter: 'brightness_contrast' }, { name: 'Levels...', target: 'ps/commands.new_adjustment_layer', parameter: 'levels' }, { name: 'Curves...', target: 'ps/commands.new_adjustment_layer', parameter: 'curves' }, { name: 'Exposure...', target: 'ps/commands.new_adjustment_layer', parameter: 'exposure' }, '-', { name: 'Vibrance...', target: 'ps/commands.new_adjustment_layer', parameter: 'vibrance' }, { name: 'Hue/Saturation...', target: 'ps/commands.new_adjustment_layer', parameter: 'hue_saturation' }, { name: 'Color Balance...', target: 'ps/commands.new_adjustment_layer', parameter: 'color_balance' }, { name: 'Black & White...', target: 'ps/commands.new_adjustment_layer', parameter: 'black_white' }, { name: 'Photo Filter...', target: 'ps/commands.new_adjustment_layer', parameter: 'photo_filter' }, { name: 'Channel Mixer...', target: 'ps/commands.new_adjustment_layer', parameter: 'channel_mixer' }, 'Color Lookup...', '-', { name: 'Invert', target: 'ps/commands.new_adjustment_layer', parameter: 'invert' }, { name: 'Posterize...', target: 'ps/commands.new_adjustment_layer', parameter: 'posterize' }, { name: 'Threshold...', target: 'ps/commands.new_adjustment_layer', parameter: 'threshold' }, { name: 'Gradient Map...', target: 'ps/commands.new_adjustment_layer', parameter: 'gradient_map' }, { name: 'Selective Color...', target: 'ps/commands.new_adjustment_layer', parameter: 'selective_color' }]],
		'Layer Content Options...',
		'-',
		['Layer Mask', ['Reveal All|ps/commands.mask_reveal_all', 'Hide All|ps/commands.mask_hide_all', 'Reveal Selection|ps/commands.mask_reveal_selection', 'Hide Selection|ps/commands.mask_hide_selection', 'From Transparency|ps/commands.mask_from_transparency', '-', 'Delete|ps/commands.mask_delete', 'Apply|ps/commands.mask_apply', '-', 'Disable|ps/commands.mask_toggle', 'Unlink']],
		['Vector Mask', ['Reveal All', 'Hide All', 'Current Path', '-', 'Delete', '-', 'Disable', 'Unlink']],
		'Create Clipping Mask|Alt+Ctrl+G|ps/commands.toggle_clipping_mask',
		'-',
		['Smart Objects', ['Convert to Smart Object', 'New Smart Object via Copy', 'Edit Contents', 'Export Contents...', 'Replace Contents...', ['Stack Mode', ['None']], 'Rasterize']],
		['Video Layers', ['New Video Layer from File...', 'New Blank Video Layer', '-', 'Insert Blank Frame', 'Duplicate Frame', 'Delete Frame', 'Replace Footage...', '-', 'Interpret Footage...', '-', 'Restore Frame', 'Restore All Frames', '-', 'Reload Frame', 'Rasterize']],
		['Rasterize', ['Type|layer/raster.raster', 'Shape|layer/raster.raster', 'Fill Content', 'Vector Mask', 'Smart Object', 'Video', '3D', '-', 'Layer|layer/raster.raster', 'All Layers|ps/commands.rasterize_all']],
		'-',
		'New Layer Based Slice',
		'-',
		'Group Layers|Ctrl+G|ps/commands.group_layers',
		'Ungroup Layers|Shift+Ctrl+G|ps/commands.ungroup_layers',
		'Hide Layers|Ctrl+,|layer/visibility.toggle',
		'-',
		['Arrange', ['Bring to Front|Shift+Ctrl+]|ps/commands.bring_to_front', 'Bring Forward|Ctrl+]|layer/move.up', 'Send Backward|Ctrl+[|layer/move.down', 'Send to Back|Shift+Ctrl+[|ps/commands.send_to_back', '-', 'Reverse|ps/commands.arrange_reverse']],
		['Combine Shapes', ['Unite Shapes', 'Subtract Front Shape', 'Unite Shapes at Overlap', 'Subtract Shapes at Overlap']],
		'-',
		['Align', ['Top Edges|ps/commands.align_top', 'Vertical Centers|ps/commands.align_vcenter', 'Bottom Edges|ps/commands.align_bottom', '-', 'Left Edges|ps/commands.align_left', 'Horizontal Centers|ps/commands.align_hcenter', 'Right Edges|ps/commands.align_right']],
		['Distribute', ['Top Edges|ps/commands.distribute_top', 'Vertical Centers|ps/commands.distribute_vcenter', 'Bottom Edges|ps/commands.distribute_bottom', '-', 'Left Edges|ps/commands.distribute_left', 'Horizontal Centers|ps/commands.distribute_hcenter', 'Right Edges|ps/commands.distribute_right']],
		'-',
		'Lock Layers...|Ctrl+/',
		'-',
		'Link Layers',
		'Select Linked Layers',
		'-',
		'Merge Down|Ctrl+E|ps/commands.merge_down',
		'Merge Visible|Shift+Ctrl+E|ps/commands.merge_visible',
		'Flatten Image|ps/commands.flatten_image',
		'-',
		['Matting', ['Defringe...|ps/commands.defringe', 'Remove Black Matte|ps/commands.remove_black_matte', 'Remove White Matte|ps/commands.remove_white_matte']],
	]],
	['Type', [
		['Panels', [{ name: 'Character Panel', target: 'ps/commands.toggle_panel', parameter: 'character' }, { name: 'Paragraph Panel', target: 'ps/commands.toggle_panel', parameter: 'paragraph' }, 'Character Styles Panel', 'Paragraph Styles Panel']],
		['Anti-Alias', ['None', 'Sharp', 'Crisp', 'Strong', 'Smooth']],
		['Orientation', ['Horizontal|ps/commands.text_horizontal', 'Vertical|ps/commands.text_vertical']],
		['OpenType', ['Contextual Alternates', 'Standard Ligatures', 'Discretionary Ligatures', 'Swash', 'Oldstyle', 'Ordinals', 'Fractions']],
		'-',
		'Extrude to 3D',
		'-',
		'Create Work Path',
		'Convert to Shape',
		'-',
		'Rasterize Type Layer|layer/raster.raster',
		'Convert to Paragraph Text',
		'Warp Text...',
		'-',
		['Font Preview Size', ['None', 'Small', 'Medium', 'Large', 'Extra Large', 'Huge']],
		['Language Options', ['Latin and CJK Features', 'Middle Eastern Features']],
		'-',
		'Update All Text Layers',
		'Replace All Missing Fonts',
		'-',
		'Paste Lorem Ipsum|ps/commands.paste_lorem_ipsum',
		'-',
		'Load Default Type Styles',
		'Save Default Type Styles',
	]],
	['Select', [
		'All|Ctrl+A|ps/commands.select_all',
		'Deselect|Ctrl+D|ps/commands.deselect',
		'Reselect|Shift+Ctrl+D|ps/commands.reselect',
		'Inverse|Shift+Ctrl+I|ps/commands.select_inverse',
		'-',
		'All Layers|Alt+Ctrl+A|ps/commands.select_all_layers',
		'Deselect Layers|ps/commands.deselect_layers',
		'Similar Layers|ps/commands.similar_layers',
		'-',
		'Color Range...|ps/commands.color_range',
		'-',
		'Refine Edge...|Alt+Ctrl+R',
		['Modify', ['Border...|ps/commands.modify_border', 'Smooth...|ps/commands.modify_smooth', 'Expand...|ps/commands.modify_expand', 'Contract...|ps/commands.modify_contract', 'Feather...|Shift+F6|ps/commands.modify_feather']],
		'-',
		'Grow|ps/commands.grow',
		'Similar|ps/commands.similar',
		'-',
		'Transform Selection|ps/commands.transform_selection',
		'-',
		{ name: 'Edit in Quick Mask Mode', target: 'ps/commands.toggle_quick_mask', checked: 'quick_mask' },
		'-',
		'Load Selection...|ps/commands.load_selection',
		'Save Selection...|ps/commands.save_selection',
		'-',
		'New 3D Extrusion',
	]],
	['Filter', [
		'Last Filter|Ctrl+F|ps/commands.last_filter',
		'-',
		'Convert for Smart Filters',
		'-',
		'Filter Gallery...|effects/browser.browser',
		'Adaptive Wide Angle...|Alt+Shift+Ctrl+A',
		'Lens Correction...|Shift+Ctrl+R',
		'Liquify...|Shift+Ctrl+X|ps/commands.liquify',
		'Oil Paint...|effects/oil.oil',
		'Vanishing Point...|Alt+Ctrl+V',
		'-',
		['Blur', ['Field Blur...', 'Iris Blur...', 'Tilt-Shift...|effects/tilt_shift.tilt_shift', '-', 'Average|ps/filters.average', 'Blur|effects/common/blur.blur', 'Blur More|effects/common/blur.blur', 'Box Blur...|effects/box_blur.box_blur', 'Gaussian Blur...|ps/filters.gaussian_blur', 'Lens Blur...', 'Motion Blur...|ps/filters.motion_blur', 'Radial Blur...|effects/zoom_blur.zoom_blur', 'Shape Blur...', 'Smart Blur...', 'Surface Blur...']],
		['Distort', ['Displace...', 'Pinch...|ps/filters.pinch', 'Polar Coordinates...|ps/filters.polar_coordinates', 'Ripple...|ps/filters.ripple', 'Shear...', 'Spherize...|ps/filters.spherize', 'Twirl...|ps/filters.twirl', 'Wave...', 'ZigZag...']],
		['Noise', ['Add Noise...|ps/filters.add_noise', 'Despeckle|effects/denoise.denoise', 'Dust & Scratches...|ps/filters.dust_scratches', 'Median...|ps/filters.median', 'Reduce Noise...|effects/denoise.denoise']],
		['Pixelate', ['Color Halftone...|effects/dot_screen.dot_screen', 'Crystallize...', 'Facet', 'Fragment', 'Mezzotint...', 'Mosaic...|effects/mosaic.mosaic', 'Pointillize...']],
		['Render', ['Clouds|ps/filters.clouds', 'Difference Clouds|ps/filters.difference_clouds', 'Fibers...', 'Lens Flare...', 'Lighting Effects...']],
		['Sharpen', ['Sharpen|effects/sharpen.sharpen', 'Sharpen Edges', 'Sharpen More|effects/sharpen.sharpen', 'Smart Sharpen...|ps/filters.smart_sharpen', 'Unsharp Mask...|ps/filters.unsharp_mask']],
		['Stylize', ['Diffuse...|ps/filters.diffuse', 'Emboss...|effects/emboss.emboss', 'Extrude...', 'Find Edges|effects/edge.edge', 'Solarize|effects/solarize.solarize', 'Tiles...', 'Trace Contour...', 'Wind...']],
		['Video', ['De-Interlace...', 'NTSC Colors']],
		['Other', ['Custom...', 'High Pass...|ps/filters.high_pass', 'Maximum...|ps/filters.maximum', 'Minimum...|ps/filters.minimum', 'Offset...|ps/filters.offset']],
		'-',
		['Digimarc', ['Embed Watermark...', 'Read Watermark...']],
		'-',
		'Browse Filters Online...',
	]],
	['3D', [
		'New 3D Layer from File...',
		'Merge 3D Layers',
		'-',
		'Export 3D Layer...',
		'-',
		'New 3D Extrusion from Selected Layer',
		'New 3D Extrusion from Selected Path',
		'New 3D Extrusion from Current Selection',
		'-',
		['New Mesh from Layer', ['Postcard', ['Mesh Preset', ['Cone', 'Cube', 'Cylinder', 'Donut', 'Hat', 'Pyramid', 'Ring', 'Soda Can', 'Sphere', 'Spherical Panorama', 'Wine Bottle']], ['Depth Map to', ['Plane', 'Two-Sided Plane', 'Cylinder', 'Sphere']], 'Volume...']],
		'-',
		'Split Extrusion',
		'-',
		'Apply Cross Section to Scene',
		'-',
		['Paint on Target Texture', ['Diffuse', 'Environment', 'Bump', 'Specular', 'Opacity', 'Shininess', 'Self-Illumination', 'Reflectivity', 'Normal']],
		'Paint Falloff...',
		'Select Paintable Areas',
		'-',
		['Create UV Overlays', ['Wireframe', 'Shaded', 'Normal Map']],
		'Reparameterize UVs...',
		'-',
		'New Tiled Painting',
		'-',
		'Make Work Path from 3D Layer',
		'-',
		'Render',
		'Sketch With Current Brush',
		'-',
		'Browse 3D Content Online...',
	]],
	['View', [
		['Proof Setup', ['Custom...', '-', 'Working CMYK', 'Working Cyan Plate', 'Working Magenta Plate', 'Working Yellow Plate', 'Working Black Plate', 'Working CMY Plates', '-', 'Legacy Macintosh RGB (Gamma 1.8)', 'Internet Standard RGB (sRGB)', 'Monitor RGB', '-', 'Color Blindness - Protanopia-type', 'Color Blindness - Deuteranopia-type']],
		'Proof Colors|Ctrl+Y',
		'Gamut Warning|Shift+Ctrl+Y',
		['Pixel Aspect Ratio', ['Custom Pixel Aspect Ratio...', 'Delete Pixel Aspect Ratio...', 'Reset Pixel Aspect Ratios...', '-', 'Square']],
		'Pixel Aspect Ratio Correction',
		'32-bit Preview Options...',
		'-',
		'Zoom In|Ctrl++|view/zoom.in',
		'Zoom Out|Ctrl+-|view/zoom.out',
		'Fit on Screen|Ctrl+0|view/zoom.auto',
		'Actual Pixels|Ctrl+1|view/zoom.original',
		'Print Size',
		'-',
		['Screen Mode', [
			{ name: 'Standard Screen Mode', target: 'ps/commands.screen_mode_standard', checked: 'screen_mode_standard' },
			{ name: 'Full Screen Mode With Menu Bar', target: 'ps/commands.screen_mode_menu', checked: 'screen_mode_menu' },
			{ name: 'Full Screen Mode', target: 'ps/commands.screen_mode_full', checked: 'screen_mode_full' },
		]],
		'-',
		{ name: 'Extras', shortcut: 'Ctrl+H', target: 'ps/commands.toggle_extras', checked: 'extras' },
		['Show', [
			'Layer Edges',
			{ name: 'Selection Edges', checked: true, target: 'ps/commands.noop' },
			'Target Path|Shift+Ctrl+H',
			{ name: 'Grid', shortcut: "Ctrl+'", target: 'view/grid.grid', checked: 'grid' },
			{ name: 'Guides', shortcut: 'Ctrl+;', target: 'ps/commands.toggle_guides', checked: 'guides' },
			'Count', 'Smart Guides', 'Slices', 'Notes', 'Pixel Grid', '3D Secondary View', '3D Ground Plane', '3D Lights', '3D Selection', 'UV Overlay', 'Mesh', 'Edit Pins', '-',
			'All', 'None', '-', 'Show Extra Options...',
		]],
		'-',
		{ name: 'Rulers', shortcut: 'Ctrl+R', target: 'ps/commands.toggle_rulers', checked: 'rulers' },
		'-',
		{ name: 'Snap', shortcut: 'Shift+Ctrl+;', target: 'ps/commands.toggle_snap', checked: 'snap' },
		['Snap To', ['Guides', 'Grid', 'Layers', 'Slices', 'Document Bounds', '-', 'All', 'None']],
		'-',
		{ name: 'Lock Guides', shortcut: 'Alt+Ctrl+;', target: 'ps/commands.lock_guides', checked: 'guides_locked' },
		'Clear Guides|ps/commands.clear_guides',
		'New Guide...|view/guides.insert',
		'-',
		'Lock Slices',
		'Clear Slices',
	]],
	['Window', [
		['Arrange', ['Tile All Vertically', 'Tile All Horizontally', '2-up Horizontal', '2-up Vertical', '3-up Horizontal', '3-up Vertical', '3-up Stacked', '4-up', '6-up', 'Consolidate All to Tabs', '-', 'Cascade', 'Tile', 'Float in Window', 'Float All in Windows', '-', 'Match Zoom', 'Match Location', 'Match Rotation', 'Match All', '-', 'New Window for Untitled-1']],
		['Workspace', [
			{ name: 'Essentials (Default)', checked: true, target: 'ps/commands.reset_workspace' },
			'3D', 'Motion', 'Painting', 'Photography', 'Typography', '-',
			'Reset Essentials|ps/commands.reset_workspace', 'New Workspace...', 'Delete Workspace...', '-',
			'Keyboard Shortcuts & Menus...|help/shortcuts.shortcuts',
		]],
		'-',
		['Extensions', ['Adobe Exchange', 'Kuler', 'Mini Bridge']],
		'-',
		'3D',
		'Actions|Alt+F9',
		{ name: 'Adjustments', target: 'ps/commands.toggle_panel', parameter: 'adjustments', checked: 'panel:adjustments' },
		'Brush|F5',
		'Brush Presets',
		{ name: 'Channels', target: 'ps/commands.toggle_panel', parameter: 'channels', checked: 'panel:channels' },
		{ name: 'Character', target: 'ps/commands.toggle_panel', parameter: 'character', checked: 'panel:character' },
		'Character Styles',
		'Clone Source',
		{ name: 'Color', shortcut: 'F6', target: 'ps/commands.toggle_panel', parameter: 'color', checked: 'panel:color' },
		'Histogram|image/histogram.histogram',
		{ name: 'History', target: 'ps/commands.toggle_panel', parameter: 'history', checked: 'panel:history' },
		{ name: 'Info', shortcut: 'F8', target: 'ps/commands.toggle_panel', parameter: 'info', checked: 'panel:info' },
		'Layer Comps',
		{ name: 'Layers', shortcut: 'F7', target: 'ps/commands.toggle_panel', parameter: 'layers', checked: 'panel:layers' },
		'Measurement Log',
		{ name: 'Navigator', target: 'ps/commands.toggle_panel', parameter: 'navigator', checked: 'panel:navigator' },
		'Notes',
		{ name: 'Paragraph', target: 'ps/commands.toggle_panel', parameter: 'paragraph', checked: 'panel:paragraph' },
		'Paragraph Styles',
		{ name: 'Paths', target: 'ps/commands.toggle_panel', parameter: 'paths', checked: 'panel:paths' },
		{ name: 'Properties', target: 'ps/commands.toggle_panel', parameter: 'properties', checked: 'panel:properties' },
		{ name: 'Styles', target: 'ps/commands.toggle_panel', parameter: 'styles', checked: 'panel:styles' },
		{ name: 'Swatches', target: 'ps/commands.toggle_panel', parameter: 'swatches', checked: 'panel:swatches' },
		'Timeline',
		'Tool Presets',
		'-',
		{ name: 'Options', target: 'ps/commands.toggle_options_bar', checked: 'options_bar' },
		{ name: 'Tools', target: 'ps/commands.toggle_toolbox', checked: 'toolbox' },
		'-',
		//open documents are appended here by workspace.update_window_menu()
	]],
	['Help', [
		'Photoshop Online Help...|F1|help/shortcuts.shortcuts',
		'Photoshop Support Center...',
		'-',
		'About pshot...|help/about.about',
		['About Plug-In', []],
		'Legal Notices...|help/about.about',
		'-',
		'Manage Extensions...',
		'-',
		'System Info...',
		'-',
		'Product Registration...',
		'Deactivate...',
		'Updates...',
		'-',
		'Photoshop Online...',
		'Photoshop Resources Online...',
		'Adobe Product Improvement Program...',
	]],
];

function parse(entry) {
	if (entry === '-') {
		return { divider: true };
	}
	if (Array.isArray(entry)) {
		return { name: entry[0], children: entry[1].map(parse) };
	}
	if (typeof entry === 'object') {
		return entry;
	}
	const parts = entry.split('|');
	const item = { name: parts[0] };
	for (let i = 1; i < parts.length; i++) {
		if (parts[i].indexOf('.') > 0 && parts[i].indexOf('/') > 0) {
			item.target = parts[i];
		}
		else {
			item.shortcut = parts[i];
		}
	}
	return item;
}

const menuDefinition = M.map(parse);

export default menuDefinition;
